application: tictactoe-2016
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# To map Appstats to the default directory (/_ah/stats/)
builtins:
- appstats: on

handlers:       # static then dynamic

- url: /_ah/spi/.*
  script: api.api
  secure: always

- url: /crons/set_announcement
  script: main.app
  login: admin

- url: /tasks/send_confirmation_email
  script: main.app
  login: admin

libraries:

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest
